Update ssd1680_simpletest.py
adafruit/Adafruit_CircuitPython_SSD1680 pull request #9
Opened 2023-02-11 20:26 UTC by dave-ct

Added comment on how to change display height for Monochrome version to work correctly

2023-02-13 18:05 UTC, tannewt reviewed
Want to add a separate example for the monochrome display?

2023-02-13 21:13 UTC, dave-ct commented
> Want to add a separate example for the monochrome display?

@tannewt  Will have a go at the weekend and update this pull request.

2023-02-14 19:28 UTC, tannewt commented
Thank you!

2023-02-15 18:24 UTC, makermelissa commented
> > Want to add a separate example for the monochrome display?
> 
> @tannewt Will have a go at the weekend and update this pull request.

I think maybe adjusting the offset by adding a `rowstart =5` parameter (possibly it may be `colstart` instead) to the init code would be the appropriate fix rather than adjusting the height which brings its own set of issues.

2023-02-15 18:36 UTC, jposada202020 commented
probably would be a good idea to verify #5 at the same time. sadly, I do not have the hardware to make the tests.

2023-02-15 20:24 UTC, dave-ct commented
@makermelissa @jposada202020 @tannewt Have made an update to the ssd1680 and simpletest example that works now on both mono and tri colour featherwings.  As cannot test on other devices have made clostart default to 1 unless set otherwise so ssd1680 will still work previous simpletest versions.

2023-02-15 20:29 UTC, dave-ct commented
Not sure why the Formatting checks have failed?

2023-02-15 20:37 UTC, jposada202020 commented
dave-ct is because of the formating.

 Error: reformatted adafruit_ssd1680.py from (https://github.com/adafruit/Adafruit_CircuitPython_SSD1680/actions/runs/4187808124/jobs/7258138283)

this is easily fixed using `pre-commit run --all-files` you could find more info here...

https://learn.adafruit.com/improve-your-code-with-pylint/check-your-code-with-pre-commit

Let me know if  you need more help :)

2023-02-15 20:53 UTC, dave-ct commented
@jposada202020 that did the job, checks all passed now.  Thanks for the pointer.

2023-02-15 21:35 UTC, jposada202020 commented
@dave-ct I will take a look over the weekend, hopefully, thanks again :)

2023-02-15 21:49 UTC, makermelissa commented
Hi, for the driver, because of the `**kwargs` in the __init__ function, you should be able to just remove the `colstart=1,` and just add `colstart` to the init code in the example and it will automatically pass through. This avoids introducing a new parameter.

Since the code is likely already in use, you should also check if it was in kwargs and default to 1 if not. This way we can have the intended functionality without breaking anything.

2023-02-15 21:54 UTC, makermelissa requested changes
Here's the changes I suggested.

2023-02-15 21:54 UTC, makermelissa commented on adafruit_ssd1680.py
> +            colstart=column_correction,
```suggestion
```

2023-02-15 21:54 UTC, makermelissa commented on adafruit_ssd1680.py
> +    def __init__(self, bus: displayio.Fourwire, column_correction=1, **kwargs) -> None:
```suggestion
    def __init__(self, bus: displayio.Fourwire, **kwargs) -> None:
        if "colstart" not in kwargs:
            kwargs["colstart"] = 1
```

2023-02-15 21:54 UTC, makermelissa commented on adafruit_ssd1680.py
> +    :param column_correction: Adjust colstart, defaults to 1 (``int``)
```suggestion
```

2023-02-15 21:54 UTC, makermelissa commented on examples/ssd1680_simpletest.py
> +    column_correction=1,
```suggestion
    colstart=1,
```

2023-02-15 22:23 UTC, dave-ct commented
@makermelissa much cleaner way than what I did.  Tested fine on my devices.

2023-02-15 22:27 UTC, makermelissa approved these changes
Looks great. thanks.

2023-02-15 22:27 UTC, merged

2023-02-16 18:59 UTC, tannewt commented
If different devices need a different colstart setting, then it'd be ideal to have separate examples for them. That's easier than reading comments and changing code.

2023-02-16 19:00 UTC, makermelissa commented
Oops, yeah. I guess I merged too soon.